### ISSUE TITLE
How to get PAS sequence?

### ISSUE THREAD

**Issue by Hoeze** [johli/aparent#1]
Hi, I'd like to annotate transcripts with differential APA.
What exactly do I have to provide as input PAS sequence?

The input to APARENT is an 205bp long sequence.
Which part of the transcript sequence do I need to select therefore?

Assuming the CSE is max. 50bp upstream the Poly-A cut, i.e. the UTR end:
It should be OK to use 130bp upstream to 75bp downstream the UTR end, shouldn't it?

**Comment by johli** [comment]
Hi!

Yes, the input to APARENT is a 205 nt long sequence.
As long as the CSE and poly-A cut site is within the input sequence with ~50 nt of padding upstream of the CSE and ~75 nt of padding downstream of the cut site, APARENT will be able to find and properly predict the cut distribution.

If I happen to know where the CSE is, I typically extract 70 nt upstream of the CSE such that the CSE is located at nt 70-76.

If I instead know only where the poly-A cut site is, I typically extract 100 nt upstream of the cut site such that the CSE is probably somewhere around nt 70.

On the other hand, if you have long transcripts and you would like to automatically find and annotate poly-A peaks, I recommend you use the peak-finding script located at (https://nbviewer.jupyter.org/github/johli/aparent/blob/master/examples/aparent_example_pas_detection.ipynb). This script slides APARENT across the sequence and outputs all peaks it could find.

There is also an interactive web app of the peak-finding script at (https://apa.cs.washington.edu/detect).


Please let me know if you have any questions or if I was unclear about something.

Best,

Johannes

**Comment by Hoeze** [comment]
Thanks for the nice explanation, Johannes!

**Comment by hgjessica** [comment]
Hi!

I run this script https://nbviewer.jupyter.org/github/johli/aparent/blob/master/examples/aparent_example_pas_detection.ipynb 
I use the example you provided, copy and paste the notebook to see if it works.

I got a value error at the  #Step 1: Detect peaks by scanning APARENT across the sequence (strided), as follows:
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 9 array(s), but instead got the following list of 3 arrays

Appreciate it if you could help me with this! Thank you.

Best,
Jessica
