### ISSUE TITLE
I can not rerun the notebook for polyA peak detection

### ISSUE THREAD

**Issue by haibol2016** [johli/aparent#4]
Hello Dear Developer,

    I am trying to run your notbook for predicting polyA sites: https://nbviewer.jupyter.org/github/johli/aparent/blob/master/examples/aparent_example_pas_detection.ipynb.  ButI got the following error.   Could you help with this error?

Thanks,
Haibo

>>> peak_ixs, polya_profile = find_polya_peaks(
...     aparent_model,
...     aparent_encoder,
...     seq,
...     sequence_stride=5,
...     conv_smoothing=True,
...     peak_min_height=0.01,
...     peak_min_distance=50,
...     peak_prominence=(0.01, None)
... )
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/aprent/lib/python3.6/site-packages/aparent/predictor/aparent_predictor.py", line 131, in find_polya_peaks
    _, cut_pred = aparent_model.predict(x=aparent_encoder([seq_slice]))
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/aprent/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/aprent/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/home/hl84w/work/mccb/bin/miniconda2/envs/aprent/lib/python3.6/site-packages/keras/engine/training_utils.py", line 102, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 9 array(s), but instead got the following list of 3 arrays: [array([[[[1.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [1.],
         [0.]],

        [[1.],
         [0.],
         [0.],
         [0.]],

        [[0.]...

**Comment by johli** [comment]
Dear user,

It must be some kind of package version issue of either tensorflow or keras.
Are you using Tensorflow 1.13.1 and Keras 2.2.4? If not, please install those versions and re-try the script.

The error message hints that the model expects 9 inputs, which is strange because APARENT requires 3 inputs.
Could you try running the python line "print(aparent_model.inputs)" inside of the notebook and post the result here, so that we can see what these 9 inputs are?

Best,

Johannes

**Comment by haibol2016** [comment]
Hello  Johannes,

   Thank you very much for your kind reply. The versions of Tensorflow and
Keras I installed are exactly as you mentioned.   The output of
aparent_model.inputs  is as follows, which contains 9 inputs.

    Do you have any idea why it is not as expected?

Best regards

Haibo

 print(aparent_model.inputs)
[<tf.Tensor 'input_1:0' shape=(?, 205, 4, 1) dtype=float32>, <tf.Tensor
'input_2:0' shape=(?, 205, 4, 1) dtype=float32>, <tf.Tensor 'input_3:0'
shape=(?, 1) dtype=float32>, <tf.Tensor 'input_4:0' shape=(?, 1)
dtype=float32>, <tf.Tensor 'input_5:0' shape=(?, 1) dtype=float32>,
<tf.Tensor 'input_6:0' shape=(?, 1) dtype=float32>, <tf.Tensor 'input_7:0'
shape=(?, 1) dtype=float32>, <tf.Tensor 'input_8:0' shape=(?, 13)
dtype=float32>, <tf.Tensor 'input_9:0' shape=(?, 1) dtype=float32>]

**Comment by johli** [comment]
Hi,

Are you sure that you are loading the basic (not APADB-refitted) version of the model, “ aparent_large_lessdropout_all_libs_no_sampleweights.h5”? This model has 3 inputs.

The APADB-fitted version, “ aparent_apadb_fitted_large_lessdropout_no_sampleweights.h5”, has 9 inputs, but cannot be used in this script.

Best,

Johannes

**Comment by haibol2016** [comment]
Hello Johli/Aparent,

    Yes, I used the  APADB-fitted version of  the model. That is the
reason. Thanks.

Haibo
