### ISSUE TITLE
question:can i reproduce this work just on my laptop,or how much computer resource i need to do this,thanksd?

### ISSUE THREAD

**Issue by miderxi** [johli/aparent#5]

**Comment by johli** [comment]
Dear miderxi,

Sorry for the slow reply (for some reason I'm not getting email notifications about github anymore).

As for you question, the answer depends on what exactly you want to reproduce:

1. If you want to use the pre-trained neural network APARENT to run some of the notebooks that make large batch predictions (e.g. predict the 40K human variants), then a laptop would suffice, but a GPU would make the analyses faster.

2. If you want to re-train the neural network APARENT on the 3.5 million training sequences, then you would definitely want to run it on a GPU (we used a p2.xlarge AWS instance to train it, which has a Tesla K80 card). It takes half a day to train on a GPU.

3. If you want to re-process the data (align / map reads and consolidate the data into the processed file of 3.5M sequences with measurements), you either need a laptop with a lot of RAM memory (32-64GB) or similarly powered machine. A GPU is not needed for this.

Best,

Johannes

**Comment by miderxi** [comment]
To my surprise,I thout it will be a sillence store in the sea,to that,I am appreciate you reply and guidance,this is very useful for me. beside,wish you happy year and good luck
best,
chenping L

---Original---

**Comment by miderxi** [comment]
我已收到邮件，会尽快处理。
